/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UniLocMenu {
    }
}
declare global {
    interface HTMLUniLocMenuElement extends Components.UniLocMenu, HTMLStencilElement {
    }
    var HTMLUniLocMenuElement: {
        prototype: HTMLUniLocMenuElement;
        new (): HTMLUniLocMenuElement;
    };
    interface HTMLElementTagNameMap {
        "uni-loc-menu": HTMLUniLocMenuElement;
    }
}
declare namespace LocalJSX {
    interface UniLocMenu {
    }
    interface IntrinsicElements {
        "uni-loc-menu": UniLocMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uni-loc-menu": LocalJSX.UniLocMenu & JSXBase.HTMLAttributes<HTMLUniLocMenuElement>;
        }
    }
}
