/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { UniFlagName } from "./flag/models";
import { UniStoreType } from "@uni/udk";
export namespace Components {
    interface UniFlag {
        "alt": string;
        "name": UniFlagName;
        "rounded": boolean;
        "src": string;
    }
    interface UniFlagShadow {
        "alt": string;
        "name": UniFlagName;
        "rounded": boolean;
        "src": string;
    }
    interface UniFlagWrap {
        "rounded": boolean;
    }
    interface UniLangMenu {
        "activeState": string;
        "feature": string;
        "languages": string;
        "mini": boolean;
        "rounded": boolean;
        "route": string;
        "routing": boolean;
        "select": string;
        "separator": string;
        "translateState": string;
        "type": UniStoreType;
    }
    interface UniLangMenuShadow {
        "activeState": string;
        "feature": string;
        "languages": string;
        "mini": boolean;
        "rounded": boolean;
        "route": string;
        "routing": boolean;
        "select": string;
        "separator": string;
        "translateState": string;
        "type": UniStoreType;
    }
    interface UniLangMenuWrap {
        "activeState": string;
        "feature": string;
        "routing": boolean;
        "separator": string;
        "translateState": string;
        "type": UniStoreType;
    }
    interface UniTranslate {
        "active": boolean;
        "end": string;
        "feature": string;
        "path": string;
        "refresh": boolean;
        "separator": string;
        "start": string;
        "type": UniStoreType;
    }
    interface UniTranslateShadow {
        "active": boolean;
        "end": string;
        "feature": string;
        "path": string;
        "refresh": boolean;
        "separator": string;
        "start": string;
        "type": UniStoreType;
    }
}
declare global {
    interface HTMLUniFlagElement extends Components.UniFlag, HTMLStencilElement {
    }
    var HTMLUniFlagElement: {
        prototype: HTMLUniFlagElement;
        new (): HTMLUniFlagElement;
    };
    interface HTMLUniFlagShadowElement extends Components.UniFlagShadow, HTMLStencilElement {
    }
    var HTMLUniFlagShadowElement: {
        prototype: HTMLUniFlagShadowElement;
        new (): HTMLUniFlagShadowElement;
    };
    interface HTMLUniFlagWrapElement extends Components.UniFlagWrap, HTMLStencilElement {
    }
    var HTMLUniFlagWrapElement: {
        prototype: HTMLUniFlagWrapElement;
        new (): HTMLUniFlagWrapElement;
    };
    interface HTMLUniLangMenuElement extends Components.UniLangMenu, HTMLStencilElement {
    }
    var HTMLUniLangMenuElement: {
        prototype: HTMLUniLangMenuElement;
        new (): HTMLUniLangMenuElement;
    };
    interface HTMLUniLangMenuShadowElement extends Components.UniLangMenuShadow, HTMLStencilElement {
    }
    var HTMLUniLangMenuShadowElement: {
        prototype: HTMLUniLangMenuShadowElement;
        new (): HTMLUniLangMenuShadowElement;
    };
    interface HTMLUniLangMenuWrapElement extends Components.UniLangMenuWrap, HTMLStencilElement {
    }
    var HTMLUniLangMenuWrapElement: {
        prototype: HTMLUniLangMenuWrapElement;
        new (): HTMLUniLangMenuWrapElement;
    };
    interface HTMLUniTranslateElement extends Components.UniTranslate, HTMLStencilElement {
    }
    var HTMLUniTranslateElement: {
        prototype: HTMLUniTranslateElement;
        new (): HTMLUniTranslateElement;
    };
    interface HTMLUniTranslateShadowElement extends Components.UniTranslateShadow, HTMLStencilElement {
    }
    var HTMLUniTranslateShadowElement: {
        prototype: HTMLUniTranslateShadowElement;
        new (): HTMLUniTranslateShadowElement;
    };
    interface HTMLElementTagNameMap {
        "uni-flag": HTMLUniFlagElement;
        "uni-flag-shadow": HTMLUniFlagShadowElement;
        "uni-flag-wrap": HTMLUniFlagWrapElement;
        "uni-lang-menu": HTMLUniLangMenuElement;
        "uni-lang-menu-shadow": HTMLUniLangMenuShadowElement;
        "uni-lang-menu-wrap": HTMLUniLangMenuWrapElement;
        "uni-translate": HTMLUniTranslateElement;
        "uni-translate-shadow": HTMLUniTranslateShadowElement;
    }
}
declare namespace LocalJSX {
    interface UniFlag {
        "alt"?: string;
        "name"?: UniFlagName;
        "rounded"?: boolean;
        "src"?: string;
    }
    interface UniFlagShadow {
        "alt"?: string;
        "name"?: UniFlagName;
        "rounded"?: boolean;
        "src"?: string;
    }
    interface UniFlagWrap {
        "rounded"?: boolean;
    }
    interface UniLangMenu {
        "activeState"?: string;
        "feature"?: string;
        "languages"?: string;
        "mini"?: boolean;
        "rounded"?: boolean;
        "route"?: string;
        "routing"?: boolean;
        "select"?: string;
        "separator"?: string;
        "translateState"?: string;
        "type"?: UniStoreType;
    }
    interface UniLangMenuShadow {
        "activeState"?: string;
        "feature"?: string;
        "languages"?: string;
        "mini"?: boolean;
        "rounded"?: boolean;
        "route"?: string;
        "routing"?: boolean;
        "select"?: string;
        "separator"?: string;
        "translateState"?: string;
        "type"?: UniStoreType;
    }
    interface UniLangMenuWrap {
        "activeState"?: string;
        "feature"?: string;
        "routing"?: boolean;
        "separator"?: string;
        "translateState"?: string;
        "type"?: UniStoreType;
    }
    interface UniTranslate {
        "active"?: boolean;
        "end"?: string;
        "feature"?: string;
        "path"?: string;
        "refresh"?: boolean;
        "separator"?: string;
        "start"?: string;
        "type"?: UniStoreType;
    }
    interface UniTranslateShadow {
        "active"?: boolean;
        "end"?: string;
        "feature"?: string;
        "path"?: string;
        "refresh"?: boolean;
        "separator"?: string;
        "start"?: string;
        "type"?: UniStoreType;
    }
    interface IntrinsicElements {
        "uni-flag": UniFlag;
        "uni-flag-shadow": UniFlagShadow;
        "uni-flag-wrap": UniFlagWrap;
        "uni-lang-menu": UniLangMenu;
        "uni-lang-menu-shadow": UniLangMenuShadow;
        "uni-lang-menu-wrap": UniLangMenuWrap;
        "uni-translate": UniTranslate;
        "uni-translate-shadow": UniTranslateShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uni-flag": LocalJSX.UniFlag & JSXBase.HTMLAttributes<HTMLUniFlagElement>;
            "uni-flag-shadow": LocalJSX.UniFlagShadow & JSXBase.HTMLAttributes<HTMLUniFlagShadowElement>;
            "uni-flag-wrap": LocalJSX.UniFlagWrap & JSXBase.HTMLAttributes<HTMLUniFlagWrapElement>;
            "uni-lang-menu": LocalJSX.UniLangMenu & JSXBase.HTMLAttributes<HTMLUniLangMenuElement>;
            "uni-lang-menu-shadow": LocalJSX.UniLangMenuShadow & JSXBase.HTMLAttributes<HTMLUniLangMenuShadowElement>;
            "uni-lang-menu-wrap": LocalJSX.UniLangMenuWrap & JSXBase.HTMLAttributes<HTMLUniLangMenuWrapElement>;
            "uni-translate": LocalJSX.UniTranslate & JSXBase.HTMLAttributes<HTMLUniTranslateElement>;
            "uni-translate-shadow": LocalJSX.UniTranslateShadow & JSXBase.HTMLAttributes<HTMLUniTranslateShadowElement>;
        }
    }
}
